// Generated by Ignite ignite.com/cli
import { Registry } from '@cosmjs/proto-signing'
import { IgniteClient } from "./client";
import { MissingWalletError } from "./helpers";
import { IgntModule as TestchainTestchain, msgTypes as TestchainTestchainMsgTypes } from './testchain/testchain'


const Client = IgniteClient.plugin([
    TestchainTestchain
]);

const registry = new Registry([
  ...TestchainTestchainMsgTypes,
  
])

export {
    Client,
    registry,
    MissingWalletError
}
